site_name: Philip Clark Technical Writing Portfolio
site_description: Technical Writing Portfolio
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

plugins:
  - search
